data_part2 = [
    # --- UNIT 6: Professional Effectiveness ---
    ("6", "Professional effectiveness mainly focuses on:", "Soft skills, habits, and mindset", "Only technical skills", "Only communication skills", "Soft skills, habits, and mindset", "Entertainment skills"),
    ("6", "Arriving early for meetings shows:", "Respect and reliability", "Fear", "Respect and reliability", "Overconfidence", "Laziness"),
    ("6", "Ideal arrival time before meetings should be:", "10-15 minutes early", "Exactly on time", "-2 minutes early", "10-15 minutes early", "30 minutes early"),
    ("6", "Which tool is used for task tracking?", "Jira", "Photoshop", "Jira", "VLC", "WhatsApp"),
    ("6", "Breaking big projects into small tasks helps in:", "Better time management", "Confusion", "Delay", "Better time management", "Laziness"),
    ("6", "If delay is expected, what should you do?", "Inform team early", "Hide the problem", "Inform team early", "Ignore deadline", "Quit work"),
    ("6", "Morning planning helps in:", "Aligning daily priorities", "Sleeping more", "Aligning daily priorities", "Entertainment", "Avoiding work"),
    ("6", "Asking questions during code review helps to:", "Understand system design", "Waste time", "Show off", "Understand system design", "Avoid work"),
    ("6", "Self-learning mainly develops:", "Independence", "Laziness", "Dependency", "Independence", "Fear"),
    ("6", "Official documentation is useful for:", "Learning best practices", "Entertainment", "Learning best practices", "Gaming", "Time pass"),
    ("6", "Which platform provides online technical courses?", "Coursera", "Netflix", "Coursera", "Instagram", "Spotify"),
    ("6", "Open-source contribution helps in:", "Building network", "Isolation", "Building network", "Reducing skills", "Losing confidence"),
    ("6", "Before suggesting innovation, you should first:", "Understand existing process", "Criticize system", "Understand existing process", "Reject rules", "Skip training"),
    ("6", "Credibility is built by:", "Delivering work consistently", "Taking more", "Delivering work consistently", "Complaining", "Taking leaves"),
    ("6", "Data-backed ideas are important because they:", "Increase acceptance", "Look attractive", "Waste time", "Increase acceptance", "Confuse management"),
    ("6", "Best time to suggest ideas is during:", "Brainstorming or meetings", "Lunch break", "High pressure", "Brainstorming or meetings", "Exit time"),
    ("6", "SOP stands for:", "Standard Operating Procedures", "System Operating Plan", "Standard Operating Procedures", "Software Output", "Service Order"),
    ("6", "Which behavior reflects positive professional attitude?", "Accepting feedback and improving", "Avoiding teamwork", "Complaining", "Accepting feedback and improving", "Ignoring mistakes"),
    ("6", "Learning from seniors helps in:", "Experience gain", "Ego building", "Experience gain", "Time waste", "Conflict"),
    ("6", "Jugaad mindset means:", "Creative problem solving", "Cheating", "Creative problem solving", "Avoiding work", "Breaking rules"),
    ("6", "Most valuable asset for professionals is:", "Time", "Mobile", "Laptop", "Time", "Money"),
    ("6", "Technology growth requires professionals to:", "Keep learning continuously", "Stop learning", "Ignore trends", "Keep learning continuously", "Avoid updates"),
    ("6", "Reputation at workplace is built by:", "Consistent delivery", "Talking more", "Consistent delivery", "Arguing", "Showing attitude"),
    ("6", "Professional journey is compared to:", "Marathon", "Race", "Sprint", "Marathon", "Game"),
    ("6", "Positive attitude helps in:", "Handling challenges", "Creating stress", "Avoiding work", "Handling challenges", "Losing focus"),
    ("6", "Persistence and dedication lead to:", "Success", "Failure", "Confusion", "Success", "Delay"),
    ("6", "Following SOP in an organization mainly helps to:", "Maintain consistency and quality", "Increase confusion", "Maintain consistency and quality", "Reduce teamwork", "Slow down"),
    ("6", "A proactive intern will:", "Take initiative and learn new skills", "Wait for instructions", "Avoid responsibility", "Take initiative and learn new skills", "Only complete tasks"),
    ("6", "What should a fresher do when facing difficulty?", "Ask for guidance and try to learn", "Quit task", "Ignore problem", "Ask for guidance and try to learn", "Blame teammates"),
    ("6", "Which quality helps in long-term career growth?", "Continuous learning attitude", "Overconfidence", "Laziness", "Continuous learning attitude", "Avoiding teamwork"),

    # --- UNIT 7: Professional Communication ---
    ("7", "Why a professional phone greeting important for freshers?", "It creates a positive first impression", "It saves Time", "It creates a positive first impression", "allows casual talk", "It hides nervousness"),
    ("7", "What is the best way for freshers to handle a missed call from senior/HR?", "Return call within working hours & apologize", "Ignore if not urgent", "Return call within working hours & apologize", "Ask 'Who is this?'", "Send missed call back"),
    ("7", "What should freshers avoid in official WhatsApp/SMS?", "Emojis, slang, memes", "Polite language", "Emojis, slang, memes", "Short replies", "Using company group"),
    ("7", "What must be the tone of an email?", "4-6 lines with clear purpose", "One-liner", "4-6 lines with clear purpose", "10+ lines", "Long stories"),
    ("7", "Correct email tone for freshers?", "Polite, neutral, no anger or slang", "Write in anger", "Polite, neutral, no anger or slang", "Use emojis", "Include personal matters"),
    ("7", "When should freshers use 'Reply All' in emails?", "Only when everyone needs the info", "Always use it", "Only when everyone needs the info", "Send Thank you to all", "Reply All for fun"),
    ("7", "What is the most important step when using AI for email drafting?", "Always review and edit before sending", "Copy-paste blindly", "Always review and edit before sending", "Ignore grammar", "Send without checking names"),
    ("7", "Good progress update to manager should include?", "Specific progress, next steps, honest delays", "Just Work going on", "Specific progress, next steps, honest delays", "No update unless asked", "Only good news"),
    ("7", "Why avoid last-minute surprises in work updates?", "It breaks trust and causes bigger issues", "It saves time", "It breaks trust and causes bigger issues", "Managers like surprises", "It shows creativity"),
    ("7", "What does active listening mean?", "Full focus on speaker, no distractions", "Think of reply while listening", "Full focus on speaker, no distractions", "Multitask", "Interrupt often"),
    ("7", "What is the polite way for freshers to disagree with senior?", "I understand your view, however...", "You are wrong", "I understand your view, however...", "Ignore and do your way", "Argue strongly"),
    ("7", "Valuing diverse opinions helps freshers in what way?", "Improve ideas and show respect", "Stick to own opinion", "Improve ideas and show respect", "Avoid teamwork", "Blame others"),
    ("7", "The collaboration for freshers means?", "Team success > individual credit", "Take all credit", "Team success > individual credit", "Avoid helping others", "Compete with team"),
    ("7", "Work hours ethics for freshers emphasize?", "Productivity during office time", "Stay late to show hard work", "Productivity during office time", "Coming late is okay", "Leave early daily"),
    ("7", "What does continuous overtime lead to?", "Burnout and reduced performance", "Better performance", "Burnout and reduced performance", "Immediate promotion", "Extra pay always"),
    ("7", "What is the ethical duty regarding company data?", "Protect confidentiality, never share", "Share on social media", "Protect confidentiality, never share", "Save on personal devices", "Discuss in public"),
    ("7", "Best response when a fresher makes a mistake?", "Own it early, apologize, focus on solutions", "Blame others", "Own it early, apologize, focus on solutions", "Hide it", "Make excuses"),
    ("7", "Why avoid slang abbreviations in professional emails?", "They make email look unprofessional", "They save time", "They make email look unprofessional", "Seniors like them", "They show creativity"),
    ("7", "Correct etiquette for email attachments?", "Mention clearly, avoid too many large files", "Send many without mention", "Mention clearly, avoid too many large files", "Attach personal photos", "Ignore file size"),
    ("7", "One email should ideally have?", "One clear purpose", "Multiple topics", "One clear purpose", "No subject", "Long attachments"),
    ("7", "Good subject line for fresher emails?", "Clear and matches content", "Vague or funny", "Clear and matches content", "Missing", "Too long"),
    ("7", "Late return of missed calls without apology can cost?", "Internship or job opportunity", "Nothing", "Internship or job opportunity", "Extra respect", "Praise"),
    ("7", "Professional language in official WhatsApp groups shows?", "Maturity and respect", "Casual attitude", "Maturity and respect", "No rules needed", "Being cool"),
    ("7", "Using 'Reply All' to say 'Thank you' is poor etiquette. Why?", "It clutters everyone's inbox", "It shows politeness", "It clutters everyone's inbox", "It increases internet usage", "It saves time"),
    ("7", "How does regular honest updates to manager help freshers?", "Build trust, avoid surprises", "Get extra work", "Build trust, avoid surprises", "Hide delays", "Show independence"),
    ("7", "What does poor active listening often cause?", "Misunderstandings and work errors", "Better understanding", "Misunderstandings and work errors", "Faster work", "More creativity"),
    ("7", "What must freshers avoid in polite disagreement?", "Sarcasm, shouting, rude tone", "Using 'however'", "Sarcasm, shouting, rude tone", "Listen first", "Respectful words"),
    ("7", "How does owning mistakes early help freshers?", "Build trust and focus on growth", "Lose respect", "Build trust and focus on growth", "Avoid responsibility", "Blame team"),
    ("7", "Why protect data confidentiality even after hours?", "Leaks can cause legal issues", "No one checks", "Leaks can cause legal issues", "It's optional", "Sharing is caring"),
    ("7", "Final takeaway for freshers on etiquettes?", "Good behavior = long-term success", "Only skills matter", "Good behavior = long-term success", "Etiquette not needed", "Ethics optional"),

    # --- UNIT 8: Work Ethics & Culture ---
    ("8", "Employer likes to find", "All of them (Skills, Soft Skills, Desire)", "Technical skills", "Soft skills", "Desire to work", "All of them"),
    ("8", "What is True?", "70% Tendency to work & 30% Skills gets opportunity", "High Marks = Job Guarantee", "More study = better job", "Boasting CV = Job", "70% Tendency to work & 30% Skills gets opportunity"),
    ("8", "Employers appreciate", "Small Projects with core efforts", "Big names of projects", "Better marks only", "Small Projects with core efforts", "So-called efforts"),
    ("8", "What is appreciated for a fresher?", "Self learning ability", "Soft skills only", "Self learning ability", "Waiting for trainer", "All of them"),
    ("8", "Which mindset is expected?", "I tried, failed, learned, fixed it", "Faculty taught me this", "I tried, failed, learned, fixed it", "I studied this in college", "AI can work for me"),
    ("8", "What is a realistic expectation of a fresher?", "First job will be a Learning job", "High package", "First job will be a Learning job", "Luxury job", "Fast Promotion"),
    ("8", "What does not fit to employer expectations?", "Unclear emails & no follow ups", "Learn fast", "Work honestly", "Grow steadily", "Unclear emails & no follow ups"),
    ("8", "Employers don't expect you to know everything", "TRUE", "TRUE", "FALSE", "", ""),
    ("8", "What does not make you better employable as fresher?", "College degree only", "Positive attitude", "College degree only", "Long term commitment", "Self Learning ability"),
    ("8", "What is the myth about high marks in college?", "High marks guarantee a job", "High marks guarantee a job", "High marks may open opportunities", "High marks get interview", "High marks still need skills"),
    ("8", "Solve problems by asking: 'Can you still try to solve...'", "Google is OFF or senior is on leave", "Google available", "ChatGPT is free", "Google is OFF or senior is on leave", "Sir taught in class"),
    ("8", "Toxic culture in workplaces is", "A real issue to pay attention", "Mostly exaggerated", "A real issue to pay attention", "Only in small companies", "A myth"),
    ("8", "Key to standing out. Show", "Learning agility and positive attitude", "Resistance to feedback", "Tardiness", "Learning agility and positive attitude", "Isolation"),
    ("8", "Which is a biggest red flag for employment?", "I already know this", "I already know this", "I learn", "Please guide me", "I made a mistake"),
    ("8", "Pressure doesn't break careers-what does?", "Attitude", "Tight deadlines", "Sudden changes", "Attitude", "Self-learning"),
    ("8", "Your college degree makes you", "Eligible while attitude makes you employable", "Employable directly", "Eligible while attitude makes you employable", "Guaranteed a job", "Ready for high package"),
    ("8", "To become indispensable early, focus on being:", "Reliable, high-quality delivery and proactive", "Unreliable with excuses", "Reliable, high-quality delivery and proactive", "Invisible in team", "Argumentative"),
    ("8", "Which factor has shifted employer focus away from pure degrees?", "Need for outcome-focused, skills-driven hiring", "Economic slowdown", "Need for outcome-focused, skills-driven hiring", "Increase in gov jobs", "Decline in tech"),
    ("8", "As a fresher, primary focus in first 1-2 years?", "Learning, skill-building, mentorship, culture", "Highest salary only", "Learning, skill-building, mentorship, culture", "Immediate promotions", "Remote work only"),
    ("8", "What is often advised over salary alone for freshers", "Experience positive culture", "Short-term high pay", "Experience positive culture", "Job hopping", "Ignoring reviews"),
    ("8", "For internship aspirants, a good opportunity offers", "Real projects and skill exposure", "Only certificate", "Real projects and skill exposure", "No stipend", "Isolation"),
    ("8", "Legally, bonds can be enforceable if", "Reasonable, protects employer interest", "Extremely high penalty", "Reasonable, protects employer interest", "Signed under pressure", "Unlimited duration"),
    ("8", "Employers don't expect freshers to", "Know everything", "Be honest", "Know everything", "Be reliable", "Be hungry to learn"),
    ("8", "Which is a common component in fresher offer letters in India?", "Probation period (3-6 months)", "Lifetime guarantee", "Probation period (3-6 months)", "No salary details", "Unlimited leaves"),
    ("8", "Why do companies use Job Agreements?", "To recover training/hiring costs", "To give free coffee", "To recover training/hiring costs", "To avoid interviews", "Nothing"),
    ("8", "Before accepting a job offer try to understand", "Bond clauses, notice period, pay", "Color of letterhead", "Bond clauses, notice period, pay", "Company logo", "Nothing"),
    ("8", "Resignation from a so called toxic culture is", "A true courage", "Take mental peace", "A true courage", "A fake mental peace", "A loss to company"),
    ("8", "When might it be okay to stay in challenging job?", "High learning/growth potential and fixable", "Severe workload", "No pay", "High learning/growth potential and fixable", "Bullying"),
    ("8", "Frequent job hops (every 6-12 months) as fresher?", "Instability to some recruiters", "Always positive", "Instability to some recruiters", "No impact", "Guaranteed hire"),
    ("8", "In today's Indian market, how are 6-8 months shifts viewed?", "Many a times red flag", "Acceptable", "Many a times red flag", "Better than long tenure", "Irrelevant"),

    # --- UNIT 9: Group Communication ---
    ("9", "Why group communication matters?", "Speed, clarity, alignment, decisions, accountability", "Wastes time", "Speed, clarity, alignment, decisions, accountability", "Creates confusion", "Delays projects"),
    ("9", "What happens when communication fails?", "Blame, confusion, delay, conflict, rework", "Smooth progress", "Blame, confusion, delay, conflict, rework", "Faster finish", "No impact"),
    ("9", "Biggest advantage of offline meetings?", "Body language, instant feedback + bonding", "No need to attend", "Body language, instant feedback + bonding", "Only remote", "Hard to schedule"),
    ("9", "What makes good offline meeting?", "Agenda, punctuality, participation, notes", "No agenda", "Agenda, punctuality, participation, notes", "Phone scrolling", "Late start"),
    ("9", "Signs of bad offline meeting?", "No agenda, late, scrolling, no outcome", "Everyone on time", "No agenda, late, scrolling, no outcome", "Active participation", "Clear decisions"),
    ("9", "Advantages of online groups?", "Fast, remote, searchable, flexible", "Slow and rigid", "Fast, remote, searchable, flexible", "No records", "Only face-to-face"),
    ("9", "Common online meeting mistakes?", "Reply All misuse, emoji overload, voice notes", "Short clear messages", "Reply All misuse, emoji overload, voice notes", "No emojis", "Quick responses"),
    ("9", "Being considerate means?", "Empathy, listening, patience to others", "Ignoring others", "Empathy, listening, patience to others", "Being rude", "Self-focused"),
    ("9", "What shows disrespect in groups?", "Interrupting, ignoring, sarcasm", "Active listening", "Interrupting, ignoring, sarcasm", "Polite tone", "Encouraging others"),
    ("9", "Minutes of Meeting should include?", "Decisions, actions, deadlines, responsibility", "Only jokes", "Decisions, actions, deadlines, responsibility", "Personal chats", "No details"),
    ("9", "Why MoM important?", "Clarity, accountability, reference record", "Wastes time", "Clarity, accountability, reference record", "Confuses everyone", "No one reads"),
    ("9", "Best during meetings?", "Avoid gadgets, use pen & paper", "Scroll phone", "Avoid gadgets, use pen & paper", "Multitask", "Record secretly"),
    ("9", "Why avoid digital distractions?", "Low attention, more mistakes", "Improves focus", "Low attention, more mistakes", "Saves time", "Everyone does it"),
    ("9", "Meeting that could be email?", "Choose right mode - many unnecessary", "All", "Choose right mode - many unnecessary", "Emails useless", "Meetings always better"),
    ("9", "Punctuality in meetings shows?", "Respect for time", "Laziness", "Respect for time", "No importance", "Casual attitude"),
    ("9", "Participation helps freshers?", "Learn faster, show engagement", "Stay silent", "Learn faster, show engagement", "Avoid responsibility", "Take credit"),
    ("9", "Taking notes helps?", "Remember decisions and actions", "Wastes paper", "Remember decisions and actions", "No need", "Only seniors note"),
    ("9", "Late replies in groups cause?", "Team delays and frustration", "Faster progress", "Team delays and frustration", "No issue", "Everyone waits"),
    ("9", "Emoji overload looks?", "Unprofessional, childish", "Very mature", "Unprofessional, childish", "Appreciated", "No effect"),
    ("9", "Voice notes in work groups?", "Not preferred - use text", "Best option", "Not preferred - use text", "Always allowed", "Mandatory"),
    ("9", "Reply All misuse causes?", "Cluttered inboxes, irritation", "Better visibility", "Cluttered inboxes, irritation", "No problem", "Everyone likes"),
    ("9", "Mindful of others' feelings means?", "Avoid harsh words, value goals", "Speak rudely", "Avoid harsh words, value goals", "Ignore emotions", "Your needs only"),
    ("9", "Active listening shows?", "Respect and learning attitude", "Disinterest", "Respect and learning attitude", "Impatience", "Distraction"),
    ("9", "Patience in discussions helps?", "Better team relations and ideas", "Finish faster", "Better team relations and ideas", "Argue more", "Ignore others"),
    ("9", "Why avoid phone scrolling?", "Shows disrespect, reduces focus", "Helps multitasking", "Shows disrespect, reduces focus", "Everyone does", "Saves time"),
    ("9", "Good meeting outcome?", "Clear decisions, assigned actions", "No decisions", "Clear decisions, assigned actions", "Only discussion", "Confusion"),
    ("9", "Searchable online groups help?", "Find past decisions easily", "Forget everything", "Find past decisions easily", "Lose info", "No records"),
    ("9", "Flexibility of online groups allows?", "Remote work, join anywhere", "Only office", "Remote work, join anywhere", "No flexibility", "Only offline"),
    ("9", "Body language in offline helps?", "Understand tone, build trust", "Hide feelings", "Understand tone, build trust", "No importance", "Words only"),
    ("9", "Instant feedback in face-to-face?", "Clarifies doubts quickly", "Causes delay", "Clarifies doubts quickly", "No need", "Slow process"),
    ("9", "Team bonding in offline?", "Feel part of team, collaborate better", "Feel isolated", "Feel part of team, collaborate better", "Avoid people", "Stay distant"),
    ("9", "No agenda leads to?", "Wasted time, unclear outcomes", "Perfect meeting", "Wasted time, unclear outcomes", "Faster decisions", "More focus"),
    ("9", "Empathy in communication means?", "Understand colleagues' needs/feelings", "Ignore others", "Understand colleagues' needs/feelings", "Be selfish", "Your goals only"),
    ("9", "Why pen & paper over gadgets?", "Reduces distractions, improves focus", "More modern", "Reduces distractions, improves focus", "Looks old", "Everyone uses phone"),
    ("9", "Key for freshers in group communication?", "Respectful, considerate, clear", "Be silent", "Respectful, considerate, clear", "Talk more", "Ignore others"),
    ("9", "Primary advantage of group communication?", "Faster decision-making", "Entertainment", "Faster decision-making", "Personal bonding", "Informal discussions"),
    ("9", "Which represents an offline meeting?", "Face-to-face interaction", "Email discussion", "WhatsApp chat", "Face-to-face interaction", "Voice note"),
    ("9", "Element major in offline but not online?", "Body language", "Emojis", "Body language", "Internet speed", "Search history"),
    ("9", "Instant feedback is associated with?", "Offline meetings", "Email", "Offline meetings", "Recorded meetings", "Notices"),
    ("9", "Feature of a good offline meeting?", "Active participation", "No agenda", "Late start", "Active participation", "Phone scrolling"),
    ("9", "Meeting without clear outcome is?", "Bad meeting", "Productive", "Effective", "Bad meeting", "Strategic"),
    ("9", "NOT a disadvantage of poor communication?", "Alignment", "Confusion", "Delay", "Alignment", "Conflict"),
    ("9", "Online office groups allow teams to work", "Remotely", "Only during meetings", "Only from office", "Remotely", "Only during office hours"),
    ("9", "Platform for professional team communication?", "Slack", "Instagram", "Slack", "Snapchat", "Telegram"),
    ("9", "Primary advantage of offline for sentiment?", "Interpretation of body language", "Searchable docs", "Interpretation of body language", "Asynchronous", "Digital tracking"),
    ("9", "Consequence of meeting without agenda?", "Ambiguous outcomes", "Increased bonding", "Instant consensus", "Ambiguous outcomes", "Enhanced spontaneity"),
    ("9", "Why is Alignment cited as critical?", "Ensure synchronized objectives", "Reduce employees", "Ensure synchronized objectives", "Eliminate accountability", "Replace written docs"),
    ("9", "Characteristic of online groups lacking in offline?", "Searchable archives", "Emotional resonance", "Physical presence", "Searchable archives", "Non-verbal cues"),
    ("9", "Emoji Overload signifies?", "Dilution of professional clarity", "High engagement", "Dilution of professional clarity", "Technical proficiency", "Efficient docs"),
    ("9", "Flexibility of platforms like Slack?", "Collaboration across time zones", "Mandates same time", "Collaboration across time zones", "Removes respect", "Prevents searchable"),
    ("9", "Risk of Late Replies?", "Bottlenecks and stagnation", "Improved accountability", "Bottlenecks and stagnation", "Higher accountability", "Better retention"),
    ("9", "Digital mistake causing notification fatigue?", "Improper Reply All", "Zoom calls", "Apathy", "Improper Reply All", "Recording meeting"),
    ("9", "Mindful of others' needs means?", "Considering effect on workflow", "Avoiding comms", "Emoji overload", "Considering effect on workflow", "Technical tone"),
    ("9", "Result of disrespectful tone?", "Breakdown of collaboration", "Increased speed", "Introductions", "Breakdown of collaboration", "Better docs"),
    ("9", "Attribute for Professional Courtesy?", "Empathy", "Aggression", "List of late people", "Empathy", "Isolationism"),
    ("9", "Why Patience is professional respect?", "Space for perspectives", "Miss deadlines", "Move offline to online", "Space for perspectives", "Eliminate MoM"),
    ("9", "Disrespect in modern office?", "Managers demanding at late evening", "Taking notes", "Voice notes", "Managers demanding at late evening", "Searchable database"),
    ("9", "Purpose of documenting Decisions in MoM?", "Prevent disputes, ensure clarity", "Record end time", "Action Items", "Prevent disputes, ensure clarity", "No agenda"),
    ("9", "Context Switching with gadgets?", "Mental drain", "Switching pens", "Verbatim recording", "Mental drain", "Change agenda"),
    ("9", "Active Listening correlates with?", "Forces brain to process before writing", "Switching colors", "MoM-Discussion", "Forces brain to process before writing", "No follow-up"),
    ("9", "Sequence of productive meeting?", "Agenda-Discussion-Action-MoM", "MoM-Discussion-Agenda", "Action-Agenda", "Agenda-Discussion-Action-MoM", "Discussion-MoM"),
    ("9", "LJET philosophy implies?", "Soft skills are vital pillars", "Technical only", "Online only", "Soft skills are vital pillars", "No pen paper"),
    ("9", "When to 'Just Put It In Email'?", "One-way dissemination, no discussion", "Complex decision", "Team bonding", "One-way dissemination, no discussion", "Body language needed"),
    ("9", "Digital Distraction leads to?", "Critical mistakes due to low attention", "Better retention", "Critical mistakes due to low attention", "Faster intros", "Empathy"),
    ("9", "Ultimate goal of Group Communication?", "Efficient decision-making", "Longer workday", "WhatsApp transition", "No paper", "Efficient decision-making"),

    # --- UNIT 10: Exit Etiquette ---
    ("10", "Earnings progression from 10k to 3L implies?", "Staying and growing leads to salary jumps", "Saves money", "Quit early for pay", "Earnings don't increase", "Staying and growing leads to salary jumps"),
    ("10", "Mindset to avoid quitting impulsively?", "Focus on long-term benefits", "Blame company", "Ignore handover", "Leave without notice", "Focus on long-term benefits"),
    ("10", "Informing manager first before HR helps?", "Demonstrate professionalism", "Create conflict", "Get approval", "Demand promo", "Demonstrate professionalism"),
    ("10", "Why follow notice period?", "Shows responsibility", "Lets you leave instantly", "Hiding knowledge", "Quitting without training", "Shows responsibility"),
    ("10", "Handover plan includes?", "Contributing positively", "Hiding knowledge", "Delaying exit", "Criticize", "Contributing positively"),
    ("10", "Offering availability after resignation?", "Maintain supportive networks", "Get paid extra", "Avoid jobs", "Makes company angry", "Maintain supportive networks"),
    ("10", "Leaving with Dignity & Gratitude means?", "Fostering appreciation", "Encouraging blame", "Promoting grief", "Fostering appreciation", "Focusing on ego"),
    ("10", "Zero Ego, Zero Grief means?", "Exiting respectfully", "Being arrogant", "Causing drama", "Exiting respectfully", "Ignoring responsibilities"),
    ("10", "Gratitude helps freshers stay longer by?", "Recognizing value in current role", "Complaining", "Demanding more", "Recognizing value in current role", "Planning secret exits"),
    ("10", "Network preservation key because?", "Damage future references if hasty", "Increase pay", "Make famous", "Shorten notice", "Damage future references if hasty"),
    ("10", "Smooth offboarding refers to?", "Handle transitions maturely", "Ignore stakeholders", "Be unprofessional", "Handle transitions maturely", "Complain publicly"),
    ("10", "Before resigning, advice?", "Clear decision, stop impulsive quitting", "Quit on whim", "Stay forever", "Clear decision, stop impulsive quitting", "Argue better"),
    ("10", "Positive tone during resignation?", "Build goodwill", "Thinking at all", "Skip work", "Build goodwill", "Force overtime"),
    ("10", "Informing well in advance allows?", "Ensure smooth handover", "Get fired", "Pack bags", "Ensure smooth handover", "Delay pay"),
    ("10", "Purpose of notice period?", "Teaching patience and commitment", "Argue better", "Punish employees", "Teaching patience and commitment", "Ship work"),
    ("10", "Handover overview role?", "Opportunity to organize thoughts", "Extra burden", "Way to hide mistakes", "Opportunity to organize thoughts", "Useless"),
    ("10", "Lessons learned in handover helps?", "Realize growth achieved", "Blame others", "Forget past", "Realize growth achieved", "Demand bonus"),
    ("10", "Q&A & sign-off encourages?", "Ensure clarity and completion", "Leave loose ends", "Be unclear", "Ensure clarity and completion", "Avoid questions"),
    ("10", "Phrasing availability politely shows?", "Professionalism strengthening networks", "Work free", "Weakness", "Professionalism strengthening networks", "Indecision"),
    ("10", "Zero Ego, Zero Grief exit?", "Respectfully, focusing on growth", "With anger", "Blaming", "Respectfully, focusing on growth", "Secretly"),
    ("10", "Expressing gratitude maintains?", "Positive mindset", "Negative vibes", "Ego battles", "Positive mindset", "Grief"),
    ("10", "Honoring commitments until last day?", "Strong work ethic", "Laziness", "Unreliability", "Strong work ethic", "Conflicts"),
    ("10", "Staying connected after exit means?", "Potential mentorship or rehire", "Disrespect", "Isolation", "Potential mentorship or rehire", "No future help"),
    ("10", "Soft exit process teaches?", "Professionalism", "Chaos", "Rudeness", "Professionalism", "Hurt"),
    ("10", "Smooth exit mindset prevents quitting by?", "Building strong resume", "Negative feedback", "Quitting for money", "Building strong resume", "No learning"),
    ("10", "Earnings slides suggest focus on?", "Patience and skill-building", "Demanding raises", "Short stints", "Patience and skill-building", "Learning"),
    ("10", "Professional behavior during resignation avoids?", "Bad reputation", "All jobs", "Promotions", "Bad reputation", "Learning"),
    ("10", "Polite resignation message instills?", "Thoughtful communication", "Hostility", "Silence", "Thoughtful communication", "Carelessness"),
    ("10", "First step deciding to leave?", "Inform reporting manager and HR", "Inform colleagues", "Stop working", "Inform reporting manager and HR", "Update LinkedIn"),
    ("10", "Who to inform formally?", "Manager and HR", "Only HR", "Friends", "Manager and HR", "Only Manager"),
    ("10", "Why inform manager first?", "For smooth transition", "Salary discussion", "Gossip", "For smooth transition", "Social reason"),
    ("10", "Purpose of discussing next steps?", "Ensure smooth exit", "Negotiate holidays", "Complain", "Ensure smooth exit", "Delay resignation"),
    ("10", "Resignation communication should be?", "Clear and professional", "Delayed", "Emotional", "Clear and professional", "Informal"),
    ("10", "Notice period means?", "Time given after resignation", "Immediate exit", "Time for hike", "Time given after resignation", "Time before joining"),
    ("10", "Why inform ahead during notice?", "Allows planning and transition", "Irresponsibility", "Confusion", "Allows planning and transition", "Reduces workload"),
    ("10", "Notice period mainly helps in?", "Business continuity", "Abrupt exit", "Vacation", "Business continuity", "Avoiding KT"),
    ("10", "Failing to serve notice affects?", "Professional reputation", "Hobbies", "Salary slip", "Professional reputation", "Friends"),
    ("10", "Notice period mentioned in?", "Offer letter", "Resume", "ID card", "Offer letter", "Exit email"),
    ("10", "KT stands for?", "Knowledge Transfer", "Keep Task", "Key Training", "Knowledge Transfer", "Known Talent"),
    ("10", "Primary purpose of KT?", "Ensure smooth handover", "Show superiority", "Avoid work", "Ensure smooth handover", "Get appreciation"),
    ("10", "KT should include?", "Pending and ongoing tasks", "Completed tasks", "Personal notes", "Pending and ongoing tasks", "Gossip"),
    ("10", "Who benefits most from KT?", "Organization and successor", "Only employee", "Competitors", "Organization and successor", "Only manager"),
    ("10", "KT should ideally be?", "Documented and clear", "Rushed", "Avoided", "Documented and clear", "Verbal only"),
    ("10", "Part of good KT practice?", "Creating handover documents", "Deleting files", "Ignoring successor", "Creating handover documents", "Withholding info"),
    ("10", "KT ensures?", "Smooth transition", "Job insecurity", "Delayed wait", "Smooth transition", "Conflicts"),
    ("10", "KT responsibility lies with?", "Resigning employee", "Manager only", "HR only", "Resigning employee", "Peers"),
    ("10", "Availability after resignation means?", "Helping if required", "Joining again", "Ignoring call", "Helping if required", "Blocking emails"),
    ("10", "Post-resignation support shows?", "Professionalism", "Egoism", "Weakness", "Professionalism", "Dependency"),
    ("10", "Availability should be?", "Limited and reasonable", "Unlimited", "Never required", "Limited and reasonable", "Forced"),
    ("10", "Helping after resignation helps in?", "Network preservation", "Burning bridges", "Loss of respect", "Network preservation", "Legal issues"),
    ("10", "Leaving with dignity means?", "Showing gratitude", "Complaining", "Arrogant", "Showing gratitude", "Refusing"),
    ("10", "Zero ego during exit?", "Respecting organization", "Demanding favors", "Showing anger", "Respecting organization", "Ignoring rules"),
    ("10", "Zero grief refers to?", "No grudges", "No emotions", "Happiness only", "No grudges", "Sadness"),
    ("10", "Why gratitude important?", "For relationships and reputation", "For rejoining", "For formality", "For relationships and reputation", "Salary hike"),
    ("10", "Professional exit impacts?", "Future opportunities", "Current job", "Personal life", "Future opportunities", "Hobbies"),
    ("10", "Network preservation means?", "Maintaining professional relations", "Blocking contacts", "Gossiping", "Maintaining professional relations", "Ignoring colleagues"),
    ("10", "Action damages dignity during exit?", "Public complaints", "Smooth KT", "Thanking team", "Public complaints", "Serving notice"),
    ("10", "Gracious exit helps in?", "Long-term career growth", "Burning bridges", "Immediate promotion", "Long-term career growth", "Avoiding notice"),
]
