data_part1 = [
    # --- UNIT 1: Interview Skills ---
    ("1", "Which of the following best explains the natural fear experienced before interviews?", "Human biological response", "Lack of intelligence", "Human biological response", "Poor academic record", "Weak communication"),
    ("1", "What do symptoms such as sweaty palms and increased heart rate indicate during interviews?", "Activation of stress response", "Physical illness", "Activation of stress response", "Fatigue", "Lack of preparation"),
    ("1", "Excessive overthinking during interviews mainly affects which of the following abilities?", "Concentration and decision-making ability", "Dressing style", "Speaking speed", "Concentration and decision-making ability", "Body posture"),
    ("1", "Why does fear negatively impact interview performance?", "Interrupts memory recall process", "Improves alertness", "Increases confidence", "Interrupts memory recall process", "Enhances focus"),
    ("1", "What does poor posture during an interview generally reflect?", "Lack of confidence", "Strong leadership", "High professionalism", "Lack of confidence", "Time management"),
    ("1", "The internship fear myth is commonly related to which concern?", "Academic performance and placement impact", "Skill development opportunities", "Industrial exposure", "Academic performance and placement impact", "Professional networking"),
    ("1", "What is the most significant benefit of internship experience for students?", "Development of practical professional skills", "Easy academic grading", "Reduced academic workload", "Development of practical professional skills", "Flexible working hours"),
    ("1", "On what basis do interviewers primarily evaluate candidates?", "Overall professional competence", "Attendance percentage", "College reputation", "Overall professional competence", "Social media profile"),
    ("1", "The ability to clearly explain technical concepts indicates which competency?", "Communication competence", "Programming speed", "Memorization ability", "Communication competence", "Writing proficiency"),
    ("1", "According to growth mindset theory, how are challenges viewed?", "Opportunities for learning and improvement", "Permanent failures", "Career threats", "Opportunities for learning and improvement", "Personal limitations"),
    ("1", "A fear-based mindset often leads to which outcome?", "Avoidance of challenging opportunities", "Faster career growth", "Higher motivation", "Avoidance of challenging opportunities", "Skill mastery"),
    ("1", "Why are mock interviews considered effective preparation tools?", "Simulate real interview environments", "Replace technical preparation", "Guarantee job selection", "Simulate real interview environments", "Reduce syllabus coverage"),
    ("1", "What is the primary purpose of practicing positive self-talk?", "Building mental confidence", "Increasing overconfidence", "Ignoring weaknesses", "Building mental confidence", "Avoiding preparation"),
    ("1", "Maintaining proper eye contact during interviews supports which aspect of communication?", "Professional engagement and confidence", "Aggressive behavior", "Disrespectful attitude", "Professional engagement and confidence", "Nervous response"),
    ("1", "What does the concept of normalizing fear refer to?", "Accepting nervousness as a natural reaction", "Avoiding interview situations", "Giving excuses for mistakes", "Accepting nervousness as a natural reaction", "Ignoring preparation"),
    ("1", "How does thorough preparation improve interview performance?", "Increasing clarity and self-confidence", "Reducing content scope", "Avoiding effort", "Increasing clarity and self-confidence", "Saving time"),
    ("1", "A strong learning attitude in candidates reflects which characteristic?", "Willingness to adapt and improve skills", "Fixed knowledge base", "Short-term thinking", "Willingness to adapt and improve skills", "Overconfidence"),
    ("1", "Cultural fit assessment in interviews primarily focuses on which factor?", "Alignment with organizational values", "Salary expectations", "Fashion preferences", "Alignment with organizational values", "Language fluency"),
    ("1", "What is a common consequence of communication breakdown during interviews?", "Misinterpretation of candidate responses", "Higher evaluation scores", "Faster interview process", "Misinterpretation of candidate responses", "Positive feedback"),
    ("1", "Stress hormones mainly interfere with which cognitive function of candidates?", "Memory performance", "Writing speed", "Voice tone", "Memory performance", "Body posture"),
    ("1", "Continuous peer comparison among students generally increases which factor?", "Psychological pressure and self-doubt", "Motivation consistency", "Academic performance", "Psychological pressure and self-doubt", "Social interaction"),
    ("1", "How can family expectations negatively affect student performance?", "Increasing internal pressure", "Improving emotional balance", "Reducing workload", "Increasing internal pressure", "Increasing relaxation"),
    ("1", "Internship experience enhances a resume primarily by providing what benefit?", "Real-world professional exposure", "Attendance records", "Classroom knowledge", "Real-world professional exposure", "Examination scores"),
    ("1", "How does a growth mindset contribute to long-term career success?", "Continuous self-improvement", "Risk avoidance", "Fixed working habits", "Continuous self-improvement", "Minimum effort"),
    ("1", "Practicing commonly asked interview questions mainly helps students in which way?", "Improving response clarity and confidence", "Memorizing fixed answers", "Avoiding preparation", "Improving response clarity and confidence", "Guessing responses"),
    ("1", "Appropriate body language during interviews demonstrates which quality?", "Confidence and professionalism", "Arrogance", "Carelessness", "Confidence and professionalism", "Nervous behavior"),
    ("1", "Technical competency in interviews refers to which ability?", "Apply knowledge to solve practical problems", "Memorize theoretical concepts", "Type quickly", "Apply knowledge to solve practical problems", "Design presentations"),
    ("1", "Effective career planning requires students to perform which action?", "Evaluate multiple career pathways", "Follow peer choices blindly", "Avoid future planning", "Evaluate multiple career pathways", "Depend on luck"),

    # --- UNIT 2: Job Search & Networking ---
    ("2", "What is the key mindset shift needed for proactive job searching?", "From 'I need a job' to 'I solve problems'", "From 'I solve problems' to 'I need a job'", "From 'I need a job' to 'I solve problems'", "From skill development to resume writing", "From networking to online applications"),
    ("2", "The T-shaped engineer concept emphasizes", "Deep technical skills + broad complementary skills", "Only deep technical knowledge", "Only broad soft skills", "Deep technical skills + broad complementary skills", "Specialization in one tool only"),
    ("2", "What should be your primary proof of skills as an engineering student?", "Project portfolio", "High GPA", "Certificate collection", "Project portfolio", "Recommendation letters"),
    ("2", "Growth mindset in job search means", "Viewing rejections as feedback", "Waiting for perfect opportunities", "Viewing rejections as feedback", "Applying only to guaranteed positions", "Avoiding challenging roles"),
    ("2", "The FIRST step in skill gap analysis", "Analyzing job descriptions in your field", "Enrolling in expensive courses", "Analyzing job descriptions in your field", "Asking friends for advice", "Waiting for college curriculum updates"),
    ("2", "Which is NOT a component of the horizontal bar in T-shaped skills?", "Technical programming depth", "Technical programming depth", "Communication skills", "Collaboration abilities", "Business acumen"),
    ("2", "Proactive learning for engineers means", "Self-initiated skill development beyond syllabus", "Waiting for college to teach everything", "Learning only from textbooks", "Memorizing interview questions", "Self-initiated skill development beyond syllabus"),
    ("2", "The most valuable approach to building skills", "Hands-on projects with documentation", "Collecting certificates without projects", "Theoretical knowledge only", "Watching tutorial videos passively", "Hands-on projects with documentation"),
    ("2", "The ideal LinkedIn headline for a 3rd year engineering student is", "Engineering Student | Python Developer | Seeking Summer Internship", "Student at XYZ College", "Seeking internship", "Engineering Student | Python Developer | Seeking Summer Internship", "Future Engineer"),
    ("2", "Which photo is appropriate for LinkedIn profile?", "Professional headshot with plain background", "Casual selfie", "Group photo cropped", "Professional headshot with plain background", "Party photo"),
    ("2", "The About section should include", "3 paragraphs: Introduction, Skills, Goals", "Only your college name", "Your entire life story", "3 paragraphs: Introduction, Skills, Goals", "Just contact information"),
    ("2", "When describing projects in Experience section, use", "STAR method (Situation, Task, Action, Result)", "Just project titles", "Emotional descriptions", "STAR method (Situation, Task, Action, Result)", "Technical jargon only"),
    ("2", "Your digital footprint includes:", "LinkedIn, GitHub, portfolio website", "Only LinkedIn", "All social media including personal", "LinkedIn, GitHub, portfolio website", "Only resume on job portals"),
    ("2", "Personalized connection requests should", "Mention how you know them or why connecting", "Be sent to everyone", "Ask for job directly", "Mention how you know them or why connecting", "Just say 'Hi'"),
    ("2", "The best time to update your LinkedIn profile is", "After completing each significant project/course", "Only when looking for job", "Once a year", "After completing each significant project/course", "Never, keep it static"),
    ("2", "Which is NOT recommended for LinkedIn profile?", "Personal political views", "Professional headline", "List of relevant skills", "Personal political views", "Project descriptions"),
    ("2", "The ideal length of a cold email is", "Less than 200 words", "500 words", "As long as needed", "Less than 200 words", "One sentence"),
    ("2", "Best days to send cold emails are", "Tuesday-Thursday, 10 AM-2 PM", "Monday mornings", "Friday evenings", "Weekends", "Tuesday-Thursday, 10 AM-2 PM"),
    ("2", "Professional email signature should include", "Name, college, contact, LinkedIn/GitHub", "Funny quote", "All social media links", "Name, college, contact, LinkedIn/GitHub", "Colorful fonts"),
    ("2", "The hook in cold email should:", "Show you researched them/company", "Be generic compliment", "Immediately ask for job", "Show you researched them/company", "Talk only about yourself"),
    ("2", "Value proposition in email means", "Explaining what you can offer", "Demanding high salary", "Listing all your achievements", "Explaining what you can offer", "Criticizing their company"),
    ("2", "Appropriate follow up time after no response", "One Week", "Next day", "One month", "One Week", "Never follow up"),
    ("2", "Which email domain is professional?", "hr@companyname.com", "companyhr@gmail.com", "jobs.company@rediffmail.com", "hr@companyname.com", "company.careers@yahoo.com"),
    ("2", "The 70/30 rule in networking conversations means:", "You listen 70%, talk 30%", "You talk 70%, listen 30%", "70% asking questions, 30% giving answers", "You listen 70%, talk 30%", "70% Technical talk, 30% personal"),
    ("2", "Best way to approach a speaker after talk", "Wait your turn, start with appreciation", "Immediately interrupt", "Hand over resume directly", "Wait your turn, start with appreciation", "Ask for job immediately"),
    ("2", "What to research before attending an event?", "Speakers, companies, topics", "Only event location", "Dress code only", "Speakers, companies, topics", "Food menu"),
    ("2", "The 30-second introduction should include:", "Name, college, interests, purpose", "Your life story", "Your GPA and marks", "Name, college, interests, purpose", "Only your name"),
    ("2", "At hackathons, networking happens with:", "Judges, sponsors, mentors, other participants", "Only winning teams", "Nobody, it's only about coding", "Judges, sponsors, mentors, other participants", "Only organizers"),
    ("2", "At alumni events, emphasize", "Common college connection", "Criticizing college facilities", "Demanding job referrals", "Common college connection", "Your superiority to alumni"),
    ("2", "What to bring to networking events?", "All of the above (Business cards, Notebook, etc)", "Multiple resumes", "Notebook and pen", "Business cards/digital card", "All of the above"),
    ("2", "When asking for LinkedIn connection after meeting:", "Mention where you met and conversation point", "Send generic invitation", "Don't connect, wait for them", "Mention where you met and conversation point", "Connect and immediately ask for job"),
    ("2", "Networking is about", "Long-term relationship building", "Getting immediate benefits", "Showing off your achievements", "Long-term relationship building", "Finding people to do your work"),

    # --- UNIT 3: Resume Writing ---
    ("3", "A recruiter wants a quick 30-second scan of skills. Which document suits best?", "Resume", "CV", "Video resume", "Resume", "Bio-data"),
    ("3", "For a research fellowship application, why is a CV preferred over a resume?", "It allows detailed academic history", "It is shorter", "It supports videos", "It allows detailed academic history", "It is ATS-friendly"),
    ("3", "Which resume element causes maximum ATS parsing errors?", "Tables and columns", "Bold headings", "Bullet points", "Tables and columns", "Section titles"),
    ("3", "A resume mentions 'Improved system performance'. Why is this weak?", "Not quantified", "Too technical", "Too long", "Not quantified", "Not ATS-friendly"),
    ("3", "Which version shows correct quantification?", "Delivered 5 projects reducing errors by 20%", "Handled 5 projects", "Worked on projects", "Delivered 5 projects reducing errors by 20%", "Projects completed"),
    ("3", "Why should Github links be included for technical roles?", "To show real code evidence", "To increase resume length", "To replace projects", "To show real code evidence", "To bypass ATS"),
    ("3", "Which resume format maximizes ATS compatibility?", "Single-column chronological", "Creative infographic", "Two-column layout", "Single-column chronological", "Canva template"),
    ("3", "A video resume is MOST useful when applying for", "Customer-facing roles", "Data analyst role", "Research roles", "Customer-facing roles", "Government jobs"),
    ("3", "Why do many ATS systems reject image-based PDFs?", "Text cannot be parsed", "Large file size", "Poor resolution", "Text cannot be parsed", "Images look unprofessional"),
    ("3", "Which metric best demonstrates impact in a resume project?", "Improved accuracy from 70% to 92%", "Used Python", "Developed model", "Improved accuracy from 70% to 92%", "Worked in team"),
    ("3", "A resume exceeds 3 pages for a fresher. What is the likely outcome?", "Immediate rejection", "Higher selection chance", "Delayed review", "Immediate rejection", "ATS prioritization"),
    ("3", "Which is the best place to insert a portfolio link?", "Header/contact section", "Footer", "Hobbies section", "Header/contact section", "References"),
    ("3", "Why do generic objectives reduce shortlisting chances?", "Not role-specific", "Too short", "ATS ignores them", "Not role-specific", "Grammar issues"),
    ("3", "Which resume change improves ATS score the MOST?", "Matching JD keywords", "Adding hobbies", "Using colors", "Matching JD keywords", "Adding photo"),
    ("3", "A resume uses uncommon section names like 'What I Know'. Why is this risky?", "ATS may not recognize sections", "Looks informal", "Recruiters dislike it", "ATS may not recognize sections", "Increases length"),
    ("3", "Which technical resume is better for a Java developer role?", "Project-centric with GitHub links", "Skill-heavy without projects", "Education-only resume", "Project-centric with GitHub links", "Creative visual resume"),
    ("3", "Why should file name be professional (e.g. Name_Resume.pdf)?", "Recruiter clarity", "ATS ranking", "File size reduction", "Recruiter clarity", "SEO optimization"),
    ("3", "Which action directly causes resume rejection despite strong skills?", "Spelling errors", "Missing hobbies", "No photo", "Spelling errors", "Short length"),
    ("3", "Which metric best fits a cloud engineer resume?", "Reduced server cost by 30%", "Designed UI", "Created diagrams", "Reduced server cost by 30%", "Attended workshop"),
    ("3", "Why are paragraphs discouraged in resumes?", "Hard to scan quickly", "They waste space", "ATS ignores them", "Hard to scan quickly", "They look academic"),
    ("3", "Which resume best fits a data science role?", "Projects with datasets & results", "Skill list only", "Long career objective", "Projects with datasets & results", "Video resume only"),
    ("3", "Why should LinkedIn and GitHub links be clickable?", "Recruiter convenience", "Design aesthetics", "ATS preference", "Recruiter convenience", "File compression"),
    ("3", "Which resume error impacts both ATS and humans?", "Inconsistent formatting", "No color", "No hobbies", "Inconsistent formatting", "No references"),
    ("3", "Why do recruiters prefer quantified internships?", "Shows learning impact", "Looks longer", "ATS ranking", "Shows learning impact", "Certification proof"),
    ("3", "Which project description is ATS-optimized?", "Keyword-aligned description", "Creative wording", "Story-based paragraph", "Keyword-aligned description", "Image-based layout"),
    ("3", "Why is resume customization important?", "Matches job description", "Design appeal", "Increases file size", "Matches job description", "Reduces effort"),
    ("3", "Which is a strong rejection reason?", "Overdesigned resume", "No extracurriculars", "Plain layout", "Overdesigned resume", "Short resume"),
    ("3", "Which resume element proves technical credibility most?", "Projects", "Certifications", "Objective", "Projects", "Hobbies"),
    ("3", "Why is STAR method useful in resumes?", "Structures quantified impact", "Improves grammar", "Reduces length", "Structures quantified impact", "ATS requirement"),
    ("3", "Which domain needs portfolio MOST?", "UI/UX", "Accounts", "Administration", "UI/UX", "HR"),

    # --- UNIT 4: Interview Questions ---
    ("4", "Which paralinguistic feature is used for showing mood/attitude?", "Tone", "Volume", "Pitch", "Tone", "Pace"),
    ("4", "Employers assess 'attitude' mainly to understand", "Willingness to learn and adapt", "Academic scores", "Dressing style", "Willingness to learn and adapt", "Age"),
    ("4", "How is problem solving skill evaluated?", "Behavioral or situational questions", "Personal questions", "Dress code", "Behavioral or situational questions", "Resume"),
    ("4", "How is confidence judged during an interview?", "Body language and clarity", "Speed of speaking", "Height", "Body language and clarity", "Accent"),
    ("4", "What is the major advantage of online interview?", "Lower cost and time saving", "No preparation required", "Less competition", "Lower cost and time saving", "Guaranteed selection"),
    ("4", "How you should answer the common interview questions?", "Be clear, honest, and relevant", "Give one word answers", "Speak very fast", "Be clear, honest, and relevant", "Give long answers"),
    ("4", "What should be the main focus of 'Tell me about yourself'?", "Professional and academic background", "Family history", "Childhood stories", "Professional and academic background", "Personal problems"),
    ("4", "What should you do if you don't know the answer?", "Admit honestly and try logically", "Remain silent", "Guess randomly", "Admit honestly and try logically", "Change the topic"),
    ("4", "Which gesture should be avoided during interviews?", "Excessive hand movements", "Natural hand movements", "Smiling politely", "Excessive hand movements", "Nodding"),
    ("4", "What does it indicate if you talk too softly?", "Nervousness", "Confidence", "Leadership", "Nervousness", "Lack of preparation"),
    ("4", "Top evaluation parameters in interviews?", "Knowledge & soft skills", "Only marks", "Only experience", "Knowledge & soft skills", "Only salary expectation"),
    ("4", "For offline interviews, most important first step?", "Reach on time with all documents", "Talk to other candidates", "Documents not required", "Reach on time with all documents", "Be casual"),
    ("4", "What should you do in an online interview?", "Video on, clean/virtual background", "Video off", "No background", "Video on, clean/virtual background", "Blur everything"),
    ("4", "Before answering any question, freshers should?", "Listen carefully, pause & think", "Answer instantly", "Talk fast", "Listen carefully, pause & think", "Interrupt interviewer"),
    ("4", "Best structure for 'Tell me about yourself'?", "SEAT-Skills, Education, Achievements, Type of person", "Only name", "Long life story", "SEAT-Skills, Education, Achievements, Type of person", "Only hobbies"),
    ("4", "Good strengths to mention as fresher?", "Reliable, adaptable, problem solver, collaborator", "Arrogance", "Laziness", "Reliable, adaptable, problem solver, collaborator", "Poor time management"),
    ("4", "Common acceptable weaknesses for freshers?", "Delegating, public speaking, impatience, saying no", "No weaknesses", "Being perfect", "Delegating, public speaking, impatience, saying no", "Lying"),
    ("4", "'Why should we hire you?' Best answer focus?", "Less training needed, fast learner", "High salary", "I am best", "Less training needed, fast learner", "No skills"),
    ("4", "Future goals in 5 years should show?", "Skill growth & expertise", "No plans", "Switch jobs often", "Skill growth & expertise", "Retire early"),
    ("4", "When facing difficult question, freshers should?", "Stay calm, ask clarification if needed", "Panic", "Give wrong answer", "Stay calm, ask clarification if needed", "Lie"),
    ("4", "What is the STAR method used for?", "Behavioural questions", "Technical questions", "Personal questions", "Behavioural questions", "Trick questions"),
    ("4", "For 'What didn't you like about last job/college'?", "Answer positively-limited practical exposure, learned self-learning", "Complain a lot", "Blame everyone", "Answer positively-limited practical exposure, learned self-learning", "Say nothing"),
    ("4", "What makes you unique? Good answer?", "Quick learner, calm under pressure, adaptable, positive", "I am perfect", "Everyone same", "Quick learner, calm under pressure, adaptable, positive", "I am lazy"),
    ("4", "One word self-description examples?", "Resilient, determined, industrious, perfectionist", "Arrogant", "Weak", "Resilient, determined, industrious, perfectionist", "Lazy"),
    ("4", "How to define success?", "Achieving goals, learning from failures, continuous growth", "Only money", "No failures", "Achieving goals, learning from failures, continuous growth", "Being famous"),
    ("4", "If best friend copies/steals, what to do?", "Report to authority-uphold honesty", "Ignore", "Help them", "Report to authority-uphold honesty", "Blame others"),
    ("4", "Disagreeing with rule/policy-best response?", "Respectfully share concern, accept final decision", "Argue strongly", "Ignore rule", "Respectfully share concern, accept final decision", "Break rule"),
    ("4", "How to handle negative remarks?", "Listen, accept constructive, ignore baseless, stay calm", "Get angry", "Argue back", "Listen, accept constructive, ignore baseless, stay calm", "Cry"),
    ("4", "First impression in interview is formed mainly from?", "Formal attire & physical appearance", "Only words", "Only resume", "Formal attire & physical appearance", "Only marks"),
    ("4", "What does an eye contact in an interview show?", "Confidence, conviction, trust", "Fear", "Arrogance", "Confidence, conviction, trust", "Disrespect"),
    ("4", "Best facial expression at start?", "Smile, pleasant expression", "Frown", "No expression", "Smile, pleasant expression", "Angry look"),
    ("4", "What is the correct posture while sitting?", "Sit straight, no leaning back", "Slouch", "Lean forward too much", "Sit straight, no leaning back", "Cross legs high"),
    ("4", "How should a handshake be?", "Firm, with eye contact & greeting", "Too strong", "Too weak", "Firm, with eye contact & greeting", "No handshake"),
    ("4", "Low voice volume in interview shows?", "Low confidence", "High confidence", "Anger", "Low confidence", "Excitement"),
    ("4", "What is the best speaking pace in interview?", "Moderate speed", "Very slow", "Very fast", "Moderate speed", "No speech"),
    ("4", "Changing pitch in speech does what?", "Grabs attention", "Bores listener", "Shows fear", "Grabs attention", "No effect"),
    ("4", "What does a correct tone reflect?", "True emotion & strengthens message", "Confusion", "Weakness", "True emotion & strengthens message", "Anger"),
    ("4", "How do pauses help while speaking in interviews?", "Listener to process information", "Show nervousness", "Waste time", "Listener to process information", "Speed up"),
    ("4", "Why correct pronunciation matters?", "Avoids ambiguity & confusion", "Sounds cool", "Shows slang", "Avoids ambiguity & confusion", "No importance"),
    ("4", "Articulation in interview means?", "Expressing ideas clearly in words", "Confusing others", "Using jargon", "Expressing ideas clearly in words", "Being silent"),

    # --- UNIT 5: Professional Behavior ---
    ("5", "You discover a dependency failure at 6 PM. Deadline 9 AM. Best step?", "Inform manager with issue, impact, and recovery plan", "Stay late quiet", "Wait for deadline", "Inform manager with issue, impact, and recovery plan", "Submit partial"),
    ("5", "You notice a safety interlock bypassed. Senior says it's common. You?", "Raise concern respectfully and ask about safety approval", "Ignore it", "Stop test publicly", "Raise concern respectfully and ask about safety approval", "Report to HR"),
    ("5", "Another team blames your module. You aren't sure. Response?", "Suggest reviewing logs together and joint debugging", "Defend code strongly", "Remain silent", "Suggest reviewing logs together and joint debugging", "Escalate immediately"),
    ("5", "Need approval, manager in meetings. Best comms?", "Send short clear email stating decision needed", "Send long email", "Casual chat", "Send short clear email stating decision needed", "Wait for weekly meet"),
    ("5", "Stuck on config issue after hours of trying. Professional approach?", "Explain what you tried and where you are stuck", "Keep trying alone", "Ask someone to do it", "Explain what you tried and where you are stuck", "Copy solution blindly"),
    ("5", "Senior-led design has a flaw. Unsure if considered. Action?", "Raise it politely as a clarifying question", "Interrupt immediately", "Stay silent", "Raise it politely as a clarifying question", "Message privately"),
    ("5", "Task assigned to team fails, your part was correct. Stance?", "Take shared responsibility and help resolve", "State it wasn't your fault", "Accept silently", "Take shared responsibility and help resolve", "Blame teammate"),
    ("5", "Deadline advanced without reduced scope. Response?", "Communicate impact and propose trade-offs", "Accept silently", "Push back emotionally", "Communicate impact and propose trade-offs", "Ignore quality"),
    ("5", "Client asks for unverified metric. Response?", "Say you will confirm and follow up", "Guess confidently", "Redirect abruptly", "Say you will confirm and follow up", "Give guess"),
    ("5", "Update delayed. Best action?", "Send brief update with revised timing", "Stay silent", "Deliver incomplete", "Send brief update with revised timing", "Wait for reminder"),
    ("5", "Dependency team not responding. Deadline near. Action?", "Loop in manager with context and evidence", "Escalate to CEO", "Wait silently", "Loop in manager with context and evidence", "Assume not needed"),
    ("5", "Overloaded when assigned new task. Response?", "Communicate workload and ask for prioritization", "Accept and hope", "Reject outright", "Communicate workload and ask for prioritization", "Delay existing"),
    ("5", "Instructions vague. Action?", "Ask clarifying questions early", "Assume and proceed", "Copy past solution", "Ask clarifying questions early", "Deliver and revise"),
    ("5", "Client requests earlier delivery risking stability. Approach?", "Explain risks and propose alternatives", "Agree immediately", "Refuse bluntly", "Explain risks and propose alternatives", "Implement workaround"),
    ("5", "Added last-minute to meeting. Behavior?", "Quickly review context and listen actively", "Attend passively", "Ask to postpone", "Quickly review context and listen actively", "Skip meeting"),
    ("5", "Senior asks for help during high-priority task. Response?", "Clarify urgency and align priorities", "Drop task immediately", "Say yes to both", "Clarify urgency and align priorities", "Ignore request"),
    ("5", "Hidden dependency could delay sprint. Response?", "Flag risk early with mitigation", "Ignore until fail", "Work extra quiet", "Flag risk early with mitigation", "Assume not your job"),
    ("5", "Two seniors give conflicting instructions. Judgment?", "Clarify priority with them or manager", "Choose convenience", "Follow last one", "Clarify priority with them or manager", "Ignore both"),
    ("5", "Shortcut saves time but violates guidelines. Integrity?", "Suggest it formally and seek approval", "Use it quietly", "Ignore guidelines", "Suggest it formally and seek approval", "Use for test only"),
    ("5", "Approved approach is inefficient. Professionalism?", "Present concerns respectfully with data", "Ignore instructions", "Complain to peers", "Present concerns respectfully with data", "Resent silently"),
    ("5", "Demo fails in front of leadership. Response?", "Acknowledge issue and explain next steps", "Panic and apologize", "Blame external", "Acknowledge issue and explain next steps", "End demo"),
    ("5", "Don't understand technical discussion. Learning mindset?", "Ask a clear, concise question", "Pretend to understand", "Google during meet", "Ask a clear, concise question", "Ignore confusion"),
    ("5", "Late requirement change. Responsibility?", "Assess impact and communicate constraints", "Implement blindly", "Ignore change", "Assess impact and communicate constraints", "Push back"),
    ("5", "Sick and cannot complete task. Reliability?", "Send an update and handover if possible", "Say nothing", "Work anyway", "Send an update and handover if possible", "Apologize later"),
    ("5", "Behavior supporting long-term success?", "Seek feedback and learn actively", "Focus only on assigned", "Avoid responsibility", "Seek feedback and learn actively", "Compare with peers"),
    ("5", "Teammate misses commitments but liked by seniors. Teamwork?", "Raise concern privately and factually", "Complain to peers", "Call out publicly", "Raise concern privately and factually", "Ignore it"),
    ("5", "Estimate effort with incomplete info. Approach?", "Provide range with assumptions", "Give exact number", "Refuse to estimate", "Provide range with assumptions", "Avoid answering"),
    ("5", "Teammate's delay blocks you. Accountability?", "Explain dependency, impact, and next steps", "Say waiting", "Blame them", "Explain dependency, impact, and next steps", "Say nothing changed"),
    ("5", "Rushed solution now or stable later? Ethics?", "Communicate trade-offs and seek alignment", "Deliver rushed", "Delay without info", "Communicate trade-offs and seek alignment", "Cancel delivery"),
    ("5", "Colleague disrespectful to junior. Professionalism?", "Address respectfully or escalate appropriately", "Ignore it", "Join in", "Address respectfully or escalate appropriately", "Post about it"),
    ("5", "Decision with incomplete data under pressure. Judgment?", "Decide and document assumptions", "Freeze", "Guess randomly", "Decide and document assumptions", "Avoid responsibility"),
    ("5", "Unclear instructions repeatedly. Efficiency?", "Ask for structured clarification", "Keep adjusting", "Ignore instructions", "Ask for structured clarification", "Complain"),
    ("5", "Contacted outside work hours non-urgent. Boundaries?", "Respond politely and schedule later", "Ignore completely", "Work immediately", "Respond politely and schedule later", "Respond rudely"),
    ("5", "Small mistake could grow. Integrity?", "Inform early and correct it", "Fix quietly", "Hope unnoticed", "Inform early and correct it", "Blame circumstances"),
    ("5", "Assist junior while managing own work. Leadership?", "Guide briefly and set boundaries", "Ignore them", "Do their work", "Guide briefly and set boundaries", "Refuse"),
    ("5", "Habit building trust early?", "Consistent communication and delivery", "Saying yes to everything", "Working silently", "Consistent communication and delivery", "Avoiding visibility"),
    ("5", "Request conflicts with policy from influential person. Integrity?", "Explain constraints and suggest alternatives", "Comply quietly", "Refuse bluntly", "Explain constraints and suggest alternatives", "Escalate"),
    ("5", "Before marking task complete. Professionalism?", "Is this clear and usable by others", "It works for me", "Deadline met", "Is this clear and usable by others", "Someone else checks"),
    ("5", "Stress makes communication abrupt. Adjustment?", "Pause and respond calmly", "Continue as-is", "Avoid comms", "Pause and respond calmly", "Show frustration"),
    ("5", "Strong engineering mindset?", "Reflect and improve", "Avoid mistakes", "Learn forced", "Reflect and improve", "Focus instructions"),
]
